
name: Continuous Delivery
on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **.py
            README.md
